allColors=[
"Aqua",
"Black",
"Blue",
"Fuchsia",
"Gray",
"Green",
"Lime",
"Maroon",
"Navy",
"Olive",
"Orange",
"Purple",
"Red",
"Silver",
"Teal",
"White",
"Yellow",
"Acid Green",
"Aero",
"Aero Blue",
"African Purple",
"Air Force Blue",
"Air Force Blue",
"Air Superiority Blue",
"Alabama Crimson",
"Alice Blue",
"Alizarin Crimson",
"Alloy Orange",
"Almond",
"Amaranth",
"Amaranth Pink",
"Amazon",
"Amber",
"American Rose",
"Amethyst",
"Android Green",
"Anti-Flash White",
"Antique Brass",
"Antique Bronze",
"Antique Fuchsia",
"Antique Ruby",
"Antique White",
"Ao (English)",
"Apple Green",
"Apricot",
"Aqua",
"Aquamarine",
"Army Green",
"Arsenic",
"Artichoke",
"Arylide Yellow",
"Ash Grey",
"Asparagus",
"Atomic Tangerine",
"Auburn",
"Aureolin",
"AuroMetalSaurus",
"Avocado",
"Awesome",
"Azure",
"Azure",
"B'dazzled Blue",
"Baby Blue",
"Baby Blue Eyes",
"Baby Pink",
"Baby Powder",
"Baker-Miller Pink",
"Ball Blue",
"Banana Mania",
"Banana Yellow",
"Barbie Pink",
"Barn Red",
"Battleship Grey",
"Bazaar",
"Beau Blue",
"Beaver",
"Beige",
"Big Dip O?ruby",
"Bisque",
"Bistre",
"Bistre Brown",
"Bitter Lemon",
"Bitter Lime",
"Bittersweet",
"Bittersweet Shimmer",
"Black",
"Black Bean",
"Black Leather Jacket",
"Black Olive",
"Blanched Almond",
"Blast-Off Bronze",
"Bleu De France",
"Blizzard Blue",
"Blond",
"Blue",
"Blue",
"Blue",
"Blue",
"Blue",
"Blue",
"Blue Bell",
"Blue Sapphire",
"Blue Violet",
"Blue Yonder",
"Blue-Gray",
"Blue-Green",
"Blueberry",
"Bluebonnet",
"Blush",
"Bole",
"Bondi Blue",
"Bone",
"Boston University Red",
"Bottle Green",
"Boysenberry",
"Brandeis Blue",
"Brass",
"Brick Red",
"Bright Cerulean",
"Bright Green",
"Bright Lavender",
"Bright Maroon",
"Bright Navy Blue",
"Bright Pink",
"Bright Turquoise",
"Bright Ube",
"Brilliant Lavender",
"Brilliant Rose",
"Brink Pink",
"British Racing Green",
"Bronze",
"Bronze Yellow",
"Brown",
"Brown",
"Brown-Nose",
"Brunswick Green",
"Bubble Gum",
"Bubbles",
"Bud Green",
"Buff",
"Bulgarian Rose",
"Burgundy",
"Burlywood",
"Burnt Orange",
"Burnt Sienna",
"Burnt Umber",
"Byzantine",
"Byzantium",
"Cadet",
"Cadet Blue",
"Cadet Grey",
"Cadmium Green",
"Cadmium Orange",
"Cadmium Red",
"Cadmium Yellow",
"Caf? Au Lait",
"Caf? Noir",
"Cal Poly Green",
"Cambridge Blue",
"Camel",
"Cameo Pink",
"Camouflage Green",
"Canary Yellow",
"Candy Apple Red",
"Candy Pink",
"Capri",
"Caput Mortuum",
"Cardinal",
"Caribbean Green",
"Carmine",
"Carmine",
"Carmine Pink",
"Carmine Red",
"Carnation Pink",
"Carnelian",
"Carolina Blue",
"Carrot Orange",
"Castleton Green",
"Catalina Blue",
"Catawba",
"Cedar Chest",
"Ceil",
"Celadon",
"Celadon Blue",
"Celadon Green",
"Celeste",
"Celestial Blue",
"Cerise",
"Cerise Pink",
"Cerulean",
"Cerulean Blue",
"Cerulean Frost",
"CG Blue",
"CG Red",
"Chamoisee",
"Champagne",
"Charcoal",
"Charleston Green",
"Charm Pink",
"Chartreuse",
"Chartreuse",
"Cherry",
"Cherry Blossom Pink",
"Chestnut",
"China Pink",
"China Rose",
"Chinese Red",
"Chinese Violet",
"Chocolate",
"Chocolate",
"Chrome Yellow",
"Cinereous",
"Cinnabar",
"Cinnamon",
"Citrine",
"Citron",
"Claret",
"Classic Rose",
"Coal",
"Cobalt",
"Cocoa Brown",
"Coconut",
"Coffee",
"Columbia Blue",
"Congo Pink",
"Cool Black",
"Cool Grey",
"Copper",
"Copper",
"Copper Penny",
"Copper Red",
"Copper Rose",
"Coquelicot",
"Coral",
"Coral Pink",
"Coral Red",
"Cordovan",
"Corn",
"Cornell Red",
"Cornflower Blue",
"Cornsilk",
"Cosmic Latte",
"Cotton Candy",
"Cream",
"Crimson",
"Crimson Glory",
"Cyan",
"Cyan",
"Cyber Grape",
"Cyber Yellow",
"Daffodil",
"Dandelion",
"Dark Blue",
"Dark Blue-Gray",
"Dark Brown",
"Dark Byzantium",
"Dark Candy Apple Red",
"Dark Cerulean",
"Dark Chestnut",
"Dark Coral",
"Dark Cyan",
"Dark Electric Blue",
"Dark Goldenrod",
"Dark Gray",
"Dark Green",
"Dark Imperial Blue",
"Dark Jungle Green",
"Dark Khaki",
"Dark Lava",
"Dark Lavender",
"Dark Liver",
"Dark Liver",
"Dark Magenta",
"Dark Midnight Blue",
"Dark Moss Green",
"Dark Olive Green",
"Dark Orange",
"Dark Orchid",
"Dark Pastel Blue",
"Dark Pastel Green",
"Dark Pastel Purple",
"Dark Pastel Red",
"Dark Pink",
"Dark Powder Blue",
"Dark Puce",
"Dark Raspberry",
"Dark Red",
"Dark Salmon",
"Dark Scarlet",
"Dark Sea Green",
"Dark Sienna",
"Dark Sky Blue",
"Dark Slate Blue",
"Dark Slate Gray",
"Dark Spring Green",
"Dark Tan",
"Dark Tangerine",
"Dark Taupe",
"Dark Terra Cotta",
"Dark Turquoise",
"Dark Vanilla",
"Dark Violet",
"Dark Yellow",
"Dartmouth Green",
"Davy's Grey",
"Debian Red",
"Deep Carmine",
"Deep Carmine Pink",
"Deep Carrot Orange",
"Deep Cerise",
"Deep Champagne",
"Deep Chestnut",
"Deep Coffee",
"Deep Fuchsia",
"Deep Jungle Green",
"Deep Lemon",
"Deep Lilac",
"Deep Magenta",
"Deep Mauve",
"Deep Moss Green",
"Deep Peach",
"Deep Pink",
"Deep Puce",
"Deep Ruby",
"Deep Saffron",
"Deep Sky Blue",
"Deep Space Sparkle",
"Deep Taupe",
"Deep Tuscan Red",
"Deer",
"Denim",
"Desert",
"Desert Sand",
"Desire",
"Diamond",
"Dim Gray",
"Dirt",
"Dodger Blue",
"Dogwood Rose",
"Dollar Bill",
"Donkey Brown",
"Drab",
"Duke Blue",
"Dust Storm",
"Dutch White",
"Earth Yellow",
"Ebony",
"Ecru",
"Eerie Black",
"Eggplant",
"Eggshell",
"Egyptian Blue",
"Electric Blue",
"Electric Crimson",
"Electric Cyan",
"Electric Green",
"Electric Indigo",
"Electric Lavender",
"Electric Lime",
"Electric Purple",
"Electric Ultramarine",
"Electric Violet",
"Electric Yellow",
"Emerald",
"Eminence",
"English Green",
"English Lavender",
"English Red",
"English Violet",
"Eton Blue",
"Eucalyptus",
"Fallow",
"Falu Red",
"Fandango",
"Fandango Pink",
"Fashion Fuchsia",
"Fawn",
"Feldgrau",
"Feldspar",
"Fern Green",
"Ferrari Red",
"Field Drab",
"Fire Brick",
"Fire Engine Red",
"Flame",
"Flamingo Pink",
"Flattery",
"Flavescent",
"Flax",
"Flirt",
"Floral White",
"Fluorescent Orange",
"Fluorescent Pink",
"Fluorescent Yellow",
"Folly",
"Forest Green",
"Forest Green",
"French Beige",
"French Bistre",
"French Blue",
"French Lilac",
"French Lime",
"French Mauve",
"French Pink",
"French Puce",
"French Raspberry",
"French Rose",
"French Sky Blue",
"French Violet",
"French Wine",
"Fresh Air",
"Fuchsia",
"Fuchsia",
"Fuchsia Pink",
"Fuchsia Rose",
"Fulvous",
"Fuzzy Wuzzy",
"SAE/ECE Amber",
]
